### ISSUE TITLE
先到Google和Edge扩展商店上个版本呗

### ISSUE THREAD

**Issue by jackdiy** [AGIUI/Earth#2]
建议啊，可能你们已经提审核了

**Comment by shadowcz007** [comment]
已经上架 https://chrome.google.com/webstore/detail/earth/mcbhfeopeloibcjmdljfheanikfhmmgk

**Comment by shadowcz007** [comment]
已经上架 https://chrome.google.com/webstore/detail/earth/mcbhfeopeloibcjmdljfheanikfhmmgk  @jackdiy
